/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operaciones_cadenas;

import javax.swing.JOptionPane;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Clipboard;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.stream.Collectors;

/**
 *
 * @author ghost
 */
public class OperacionesLenguajes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OperacionesLenguajes.class.getName());

private void copiarAlPortapapeles(String texto) {
    StringSelection seleccion = new StringSelection(texto);
    Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
    portapapeles.setContents(seleccion, null);
    JOptionPane.showMessageDialog(this, "Resultado copiado al portapapeles");
}
// Método para limpiar el texto del usuario y convertirlo en un conjunto de palabras válidas
private Set<String> limpiarYSeparar(String texto) {
    return Arrays.stream(texto.split(","))
            .map(s -> s.replaceAll("\\s+", "")) // elimina todos los espacios, tabs, saltos de línea
            .filter(s -> !s.isEmpty())          // descarta cadenas vacías
            .collect(Collectors.toSet());
}

    

    
    public OperacionesLenguajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCopiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtL1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnInvertir = new javax.swing.JButton();
        btnConcat = new javax.swing.JButton();
        btnContar = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPotencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnUnion = new javax.swing.JButton();
        btnInterseccion = new javax.swing.JButton();
        btnDiferencia = new javax.swing.JButton();
        btncomplemento = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtuniverso = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtL2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setLocation(new java.awt.Point(700, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Operaciones con Lenguajes");

        jLabel2.setText("Ingrese texto:");

        btnCopiar.setText("Copiar Texto");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        txtResultado.setEditable(false);
        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCopiar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCopiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtL1.setColumns(20);
        txtL1.setRows(5);
        jScrollPane2.setViewportView(txtL1);

        btnInvertir.setText("Invertir");
        btnInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvertirActionPerformed(evt);
            }
        });

        btnConcat.setText("Concatenación");
        btnConcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcatActionPerformed(evt);
            }
        });

        btnContar.setText("Longitud");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });

        btnPotencia.setText("Potencia");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        jLabel4.setText("(Texto 1 + Texto 2)");

        txtPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPotenciaActionPerformed(evt);
            }
        });

        jLabel5.setText("Ingrese el numero de veces:");

        btnUnion.setText("Unión");
        btnUnion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnionActionPerformed(evt);
            }
        });

        btnInterseccion.setText("Intersección");
        btnInterseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterseccionActionPerformed(evt);
            }
        });

        btnDiferencia.setText("Diferencia");
        btnDiferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiferenciaActionPerformed(evt);
            }
        });

        btncomplemento.setText("Complemento");
        btncomplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomplementoActionPerformed(evt);
            }
        });

        txtuniverso.setColumns(20);
        txtuniverso.setRows(5);
        jScrollPane4.setViewportView(txtuniverso);

        jLabel6.setText("Defina el Lenguaje universo en el siguiente campo (si tiene)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPotencia)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInvertir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConcat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInterseccion))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnContar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addComponent(btncomplemento)
                            .addComponent(btnDiferencia)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvertir)
                    .addComponent(btnConcat)
                    .addComponent(btnUnion)
                    .addComponent(btnInterseccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDiferencia)
                .addGap(18, 18, 18)
                .addComponent(btncomplemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContar)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPotencia)
                    .addComponent(txtPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)))
        );

        txtL2.setColumns(20);
        txtL2.setRows(5);
        jScrollPane3.setViewportView(txtL2);

        jLabel3.setText("Ingrese texto 2 para concatenacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvertirActionPerformed
            String texto = txtL1.getText();
                if (texto.isEmpty()) {
        texto = "λ"; // Cadena vacía
        txtResultado.setText("[λ] // Cadena vacia");
    }
                else{     
            String invertido = new StringBuilder(texto).reverse().toString();
            txtResultado.setText("["+ invertido + "]");}
    }//GEN-LAST:event_btnInvertirActionPerformed

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
          String texto = txtL1.getText();
          String texto2 = txtL2.getText();
          
          String textototal =   texto + texto2;
          
            txtResultado.setText("Cantidad de caracteres: " + textototal.length());
    }//GEN-LAST:event_btnContarActionPerformed

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        btnCopiar.addActionListener(e -> copiarAlPortapapeles(txtResultado.getText()));
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnConcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcatActionPerformed
        String[] l1 = txtL1.getText().split(",");
        String[] l2 = txtL2.getText().split(",");
        Set<String> concatenacion = new HashSet<>();
        for (String s1 : l1) {
            for (String s2 : l2) {
                concatenacion.add(s1.trim() + s2.trim());
            }
        }
        txtResultado.setText("Concatenación:\n" +  concatenacion);
    }//GEN-LAST:event_btnConcatActionPerformed

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
       String texto = txtL1.getText();
        String potenciaStr = txtPotencia.getText();

        try {
            int potencia = Integer.parseInt(potenciaStr);

            if (potencia < 0) {
                txtResultado.setText("La potencia debe ser un número positivo.");
                return;
            }

            String resultado = texto.repeat(potencia);
            txtResultado.setText("["+ resultado + "]");

        } catch (NumberFormatException ex) {
            txtResultado.setText("Ingrese un número válido en el campo de potencia.");
        }
    }//GEN-LAST:event_btnPotenciaActionPerformed

    private void txtPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPotenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPotenciaActionPerformed

    private void btnUnionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnionActionPerformed
        String l1 = txtL1.getText().trim();
    String l2 = txtL2.getText().trim();
    
    Set<Character> union = new LinkedHashSet<>();
    for (char c : l1.toCharArray()) union.add(c);
    for (char c : l2.toCharArray()) union.add(c);

    StringBuilder resultado = new StringBuilder();
    for (char c : union) resultado.append(c);

    txtResultado.setText(resultado.toString().isEmpty() ? "ε" : resultado.toString());
    }//GEN-LAST:event_btnUnionActionPerformed

    private void btnInterseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterseccionActionPerformed
        String l1 = txtL1.getText().trim();
    String l2 = txtL2.getText().trim();

    Set<Character> set1 = new HashSet<>();
    for (char c : l1.toCharArray()) set1.add(c);

    Set<Character> interseccion = new LinkedHashSet<>();
    for (char c : l2.toCharArray()) {
        if (set1.contains(c)) interseccion.add(c);
    }

    StringBuilder resultado = new StringBuilder();
    for (char c : interseccion) resultado.append(c);

    txtResultado.setText(resultado.toString().isEmpty() ? "ε" : resultado.toString());
    }//GEN-LAST:event_btnInterseccionActionPerformed

    private void btnDiferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiferenciaActionPerformed
        String l1 = txtL1.getText().trim();
    String l2 = txtL2.getText().trim();

    Set<Character> set2 = new HashSet<>();
    for (char c : l2.toCharArray()) set2.add(c);

    StringBuilder resultado = new StringBuilder();
    for (char c : l1.toCharArray()) {
        if (!set2.contains(c)) resultado.append(c);
    }

    txtResultado.setText(resultado.toString().isEmpty() ? "ε" : resultado.toString());
    }//GEN-LAST:event_btnDiferenciaActionPerformed

    private void btncomplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomplementoActionPerformed
     // Obtener los textos de los campos
    String universoStr = txtuniverso.getText().trim();
    String l1Str = txtL1.getText().trim();
    String l2Str = txtL2.getText().trim();
    
    // Verificar que el universo no esté vacío
    if (universoStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error: Debe ingresar el universo");
        return;
    }
    
    // Separar los elementos (asumiendo que están separados por comas)
    Set<String> universo = new HashSet<>(Arrays.asList(universoStr.split("\\s*,\\s*")));
    Set<String> lenguaje = new HashSet<>();
    
    // Agregar elementos de L1 y L2 al lenguaje
    if (!l1Str.isEmpty()) {
        lenguaje.addAll(Arrays.asList(l1Str.split("\\s*,\\s*")));
    }
    if (!l2Str.isEmpty()) {
        lenguaje.addAll(Arrays.asList(l2Str.split("\\s*,\\s*")));
    }
    
    // Validar que el lenguaje esté contenido en el universo
    Set<String> fueraDelUniverso = new HashSet<>(lenguaje);
    fueraDelUniverso.removeAll(universo);
    
    if (!fueraDelUniverso.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Error: Las siguientes palabras no están en el universo:\n" + 
            String.join(", ", fueraDelUniverso));
        return;
    }
    
    // Calcular el complemento
    Set<String> complemento = new HashSet<>(universo);
    complemento.removeAll(lenguaje);
    
    // Mostrar el resultado
    if (complemento.isEmpty()) {
        txtResultado.setText("ε");
    } else {
        txtResultado.setText(String.join(", ", complemento));
    }
    }//GEN-LAST:event_btncomplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OperacionesLenguajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcat;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnDiferencia;
    private javax.swing.JButton btnInterseccion;
    private javax.swing.JButton btnInvertir;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnUnion;
    private javax.swing.JButton btncomplemento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtL1;
    private javax.swing.JTextArea txtL2;
    private javax.swing.JTextField txtPotencia;
    private javax.swing.JTextArea txtResultado;
    private javax.swing.JTextArea txtuniverso;
    // End of variables declaration//GEN-END:variables
}
